Task1:-

In [13]:
import numpy as np

arr1 = np.arange(1, 11)
arr2 = np.arange(1, 10).reshape(3, 3)
arr3 = np.random.rand(3, 5, 3)

print("1D Array:\n", arr1)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data type:", arr1.dtype)

print("\n2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)

print("\n3D Array:\n", arr3)
print("Shape:", arr3.shape)
print("Size:", arr3.size)
print("Data type:", arr3.dtype)


1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int64

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int64

3D Array:
 [[[0.68754399 0.09010342 0.20186653]
  [0.08849085 0.64899261 0.03194497]
  [0.31360209 0.22481488 0.31535445]
  [0.07315587 0.35842889 0.41887012]
  [0.89977696 0.79744922 0.62619691]]

 [[0.57337524 0.49919387 0.84893233]
  [0.13746073 0.92712336 0.74983901]
  [0.53127662 0.54792268 0.02815986]
  [0.92840913 0.80154543 0.07220137]
  [0.93341012 0.50347894 0.85867391]]

 [[0.33061877 0.2782752  0.86255176]
  [0.05271953 0.06112912 0.84332504]
  [0.13625741 0.34951044 0.77629193]
  [0.51834235 0.55725132 0.64390371]
  [0.73282426 0.49458569 0.19133431]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64


Task 2:-

In [20]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

first3 = arr[:3]
alts = arr[::2]
rev = arr[::-1]

print("Original array:", arr)
print("First three elements:", first3)
print("Alternate elements:", alts)
print("Reversed array:", rev)

Original array: [10 20 30 40 50 60 70 80 90]
First three elements: [10 20 30]
Alternate elements: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


Task 3:-

In [26]:

a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

print("a:", a)
print("b:", b)

print("\nElement-wise addition:", a + b)
print("Element-wise subtraction:", a - b)
print("Element-wise multiplication:", a * b)
print("Element-wise division:", a / b)

dp = np.dot(a, b)
print("\nDot product:", dp)

print("\nMean of a:", a.mean())
print("Median of a:", np.median(a))
print("Standard deviation of a:", a.std())
print("Variance of a:", a.var())

print("\nMax of b:", b.max(), "at index", b.argmax())
print("Min of b:", b.min(), "at index", b.argmin())


a: [14 12  2 16  2]
b: [13  9  9 18  2]

Element-wise addition: [27 21 11 34  4]
Element-wise subtraction: [ 1  3 -7 -2  0]
Element-wise multiplication: [182 108  18 288   4]
Element-wise division: [1.07692308 1.33333333 0.22222222 0.88888889 1.        ]

Dot product: 600

Mean of a: 9.2
Median of a: 12.0
Standard deviation of a: 6.013318551349164
Variance of a: 36.160000000000004

Max of b: 18 at index 3
Min of b: 2 at index 4


Task 4:-

In [31]:

arr = np.arange(1, 13)
arr2d = arr.reshape(4, 3)
arr3d = arr.reshape(2, 2, 3)
arr2dt = arr2d.T

print("Original 1D array:\n", arr)
print("\nReshaped to 2D (4x3):\n", arr2d)
print("\nReshaped to 3D (2x2x3):\n", arr3d)
print("\nTranspose of 2D array:\n", arr2dt)
print("Shape of transposed 2D array:", arr2dt.shape)


Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transpose of 2D array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape of transposed 2D array: (3, 4)


Task 5:-

In [32]:

arr = np.random.randint(10, 51, 15)
print("Original array:\n", arr)

gt25 = arr[arr > 25]
print("\nElements greater than 25:\n", gt25)

arr[arr < 30] = 0
print("\nAfter replacing elements < 30 with 0:\n", arr)

count5 = np.sum(arr % 5 == 0)
print("\nNumber of elements divisible by 5:", count5)


Original array:
 [50 17 24 34 24 36 32 20 44 39 29 22 42 48 30]

Elements greater than 25:
 [50 34 36 32 44 39 29 42 48 30]

After replacing elements < 30 with 0:
 [50  0  0 34  0 36 32  0 44 39  0  0 42 48 30]

Number of elements divisible by 5: 8


Task 6:-

In [33]:

arrspace = np.linspace(0, 1, 10)
print("Equally spaced array:\n", arrspace)

eye4 = np.eye(4)
print("\n4x4 Identity matrix:\n", eye4)

arrrand = np.random.randint(1, 101, 20)
arrsorted = np.sort(arrrand)
top5 = arrsorted[-5:]

print("\nRandom array:\n", arrrand)
print("Sorted array:\n", arrsorted)
print("5 largest elements:\n", top5)


Equally spaced array:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

4x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random array:
 [61 78 67 86 21 30 17 99 15 44 45  3 82 34 85 90 27 64 91 61]
Sorted array:
 [ 3 15 17 21 27 30 34 44 45 61 61 64 67 78 82 85 86 90 91 99]
5 largest elements:
 [85 86 90 91 99]


Task 7:-

In [35]:
import time

a = np.random.rand(100, 100)
b = np.random.rand(100, 100)

t1 = time.time()
c = np.dot(a, b)
det = np.linalg.det(c)

inv = None
if det != 0:
    inv = np.linalg.inv(c)

t2 = time.time()
elapsed = t2 - t1

print("Determinant of result matrix:", det)
if inv is not None:
    print("Inverse calculated successfully.")
else:
    print("Inverse not possible (determinant is zero).")

print("Time taken (seconds):", elapsed)

Determinant of result matrix: 7.251021632305108e+49
Inverse calculated successfully.
Time taken (seconds): 0.12825632095336914
