**Make a custom exception.**
**Make a 2-d array and read and write it in a csv format**

In [1]:
class DivideError(Exception):
    def __init__(self, msg):
        super().__init__(msg)

def safe_div(x, y):
    if y == 0:
        raise DivideError("Division by zero is not allowed.")
    return x / y

try:
    ans = safe_div(10, 0)
    print("Result:", ans)
except DivideError as err:
    print("Custom Exception Caught:", err)

Custom Exception Caught: Division by zero is not allowed.


In [2]:
# Task 2
import numpy as np
import csv
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

with open('matrix_data.csv', 'w', newline='') as fout:
    csv_writer = csv.writer(fout)
    csv_writer.writerows(matrix)
print("Matrix written to 'matrix_data.csv'")

loaded = []
with open('matrix_data.csv', 'r') as fin:
    csv_reader = csv.reader(fin)
    for line in csv_reader:
        loaded.append([int(val) for val in line])

loaded_matrix = np.array(loaded)
print("Matrix read from 'matrix_data.csv':")
print(loaded_matrix)

Matrix written to 'matrix_data.csv'
Matrix read from 'matrix_data.csv':
[[10 20 30]
 [40 50 60]
 [70 80 90]]
